name: Terraform CI/CD

#on:
  #push:
   # branches: [dev, main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    # This triggers manual approval for production
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.ref == 'refs/heads/main' && 'eu-west-1' || 'eu-north-1' }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          terraform plan -var-file="dev.tfvars"
        else
          terraform plan -var-file="prod.tfvars"
        fi
      
    - name: Terraform Apply
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          terraform apply -var-file="dev.tfvars" -auto-approve
        else
          terraform apply -var-file="prod.tfvars" -auto-approve
        fi
